### ISSUE TITLE
Floating point math library

### ISSUE THREAD

**Issue by ArthurBrussee** [Unity-Technologies/Unity.Mathematics#11]
Currently functions redirect to System.Math, casting the input to a double and output to float. In .Net Core MathF is available to do native floating point math and speed this up.

I imagine System.MathF cannot be used in unity currently, but if this is possible at some point it might be impossible to switch without breaking code relying on exact precision.

I'm not sure what Burst compiles eg System.Math.Cos too anyway - would it internally already use 32 bit cosf routine?

**Comment by xoofx** [comment]
> I imagine System.MathF cannot be used in unity currently, but if this is possible at some point it might be impossible to switch without breaking code relying on exact precision.

Precision would not change that much, as you said the API surface is currently in float, so even if there can be a float->double->float internal intermediate calculations, this should not much change the precision of the function overall (from an API contract point of view). Mono also has a pretty bad precision behavior on many front regarding the math API.

> I'm not sure what Burst compiles eg System.Math.Cos too anyway - would it internally already use 32 bit cosf routine?

Yes, it is currently remapped to plain float operations.
