### ISSUE TITLE
Very slow il2cpp (without burst) compared to System.Math

### ISSUE THREAD

**Issue by kamyker** [Unity-Technologies/Unity.Mathematics#125]
Reason: https://issuetracker.unity3d.com/issues/il2cpp-static-constructors-cause-unnecessary-wait-time-s-il2cppmethodinitialized-and-il2cpp-runtime-class-init-checks

> sin is ~15 times slower than (float)Math.Sin

**Comment by kamyker** [comment]
Could be fixed by aggressive inlining
` [MethodImpl( MethodImplOptions.AggressiveInlining )]
        public static float sin(float x) { return (float)System.Math.Sin(x); }`

https://forum.unity.com/threads/unity-mathematics-available-on-github.526100/page-8#post-5752339

**Comment by unpacklo** [comment]
I think this is fixed with #155. Closing this issue for now. I'm hoping we will have a new Mathematics release in a month or so if you find that the performance is still poor, we can reopen this.
