### ISSUE TITLE
Inverse Hyperbolic functions

### ISSUE THREAD

**Issue by lieene** [Unity-Technologies/Unity.Mathematics#143]
Can Inverse Hyperbolic functions be added to math lab?

**Comment by unpacklo** [comment]
This is currently not a high priority for our team. Could you explain what your use case is so we have a better idea of what you're using it for?

**Comment by lieene** [comment]
I was using it for dynamic simulation. Integration of high-speed motion in Air resistance.  But it's okay to use 
`        public static float coth(float x) => 1 / tanh(x);
         public static float atanh(float x) => 0.5f * log((1 + x) / (1 - x));
`  and others for now
