### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dudu502** [Unity-Technologies/Unity.Mathematics#151]
Hi, developers, do you have any plans to develop the consistency of floating point calculation?

**Comment by unpacklo** [comment]
Sorry, I don't understand your question. Are you referring to floating point determinism?

**Comment by dudu502** [comment]
> Sorry, I don't understand your question. Are you referring to floating point determinism?

Yes,That's what I want to ask,Thank you.

**Comment by unpacklo** [comment]
Floating point determinism is mostly a feature that will be delivered by the burst compiler. We don't yet have a timeline for when that will be completed and available. Unity.Mathematics will work with burst to be sure that if you rely on determinism, that you will get it.

**Comment by unpacklo** [comment]
As for when determinism will be available, we don't have timelines to share for this feature, so please keep an eye out for updates!
