### ISSUE TITLE
Equals override does not check for the type

### ISSUE THREAD

**Issue by visose** [Unity-Technologies/Unity.Mathematics#153]
The non generic Equals methods directly cast the object to the specific type without checking first. This throws an exception when comparing an object of a different type, it should return false. 

I ran into this issue trying to serialize an int3 field to json. Some serialization libraries, such as Newtonsoft Json.NET, rely on this method being properly implemented.

**Comment by Arugin** [comment]
Same problem here

**Comment by unpacklo** [comment]
@visose and @Arugin could you check the PR above to see if it your issue?

**Comment by visose** [comment]
Yes, that looks like it would fix the problem I had almost 5 months ago 😄
