### ISSUE TITLE
[Feature Request] projection function

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/Unity.Mathematics#18]
I was playing with ECS today, and I was looking for a function to project a float3 onto a plane described by a normal float3. It looks like projection functions don't exist yet (?).

**Comment by deplinenoise** [comment]
We don't have functions for this as the library is modeled on HLSL which also doesn't have that. That said, the math involved is just a dot product and a subtraction. If you feel this is important to have in the library, maybe put a PR up?

**Comment by AurelWu** [comment]
@deplinenoise maybe it would be useful to have a Mathematics.Utility or similar namespace contains methods to solve common problem available (maybe as extension methods). stuff like Vector3.Distance, the mentioned projections etc.

**Comment by macton** [comment]
We do have math.distance and math.length and math.lengthSquared.

**Comment by deplinenoise** [comment]
Mathematics will stay low-level and higher-level abstractions will be relegated to extension packages.
