### ISSUE TITLE
math.tzcnt gives incorrect results for long and ulong

### ISSUE THREAD

**Issue by weichx** [Unity-Technologies/Unity.Mathematics#182]
Unless I totally don't understand this instruction, it seems like tzcnt isn't handling longs correctly when they have more than 32 bits set. Here are some sample inputs I ran

````
// correct if value is in integer range
math.tzcnt((ulong)(1 << 4)) == 4 
math.tzcnt((ulong)(1 << 30)) == 30

// incorrect if value is greater than integer range
math.tzcnt((ulong)(1 << 33))  == 1
math.tzcnt((ulong)(1 << 40)) == 8
````
I would expect the second two examples to return 33 and 40 respectively. 
I should add that this running without burst, just managed c#. I have no idea if burst does the correct thing or not
(Edit burst also returns the same values as managed after all)

**Comment by unpacklo** [comment]
To clarify, I think the issue you're having here is the `(1 << 33)` is being treated as a signed 32 bit integer shift and the shift count of 33 will be truncated. Specifically, on page 180 of this doc https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf

<img width="822" alt="image" src="https://user-images.githubusercontent.com/3121968/100276510-87427e80-2f16-11eb-8b9c-01fc2f8a40c8.png">

Try using `1ul` instead for the shift!

**Comment by weichx** [comment]
Thanks for following up, I closed this for exactly that reason, I think everything is fine now :)
