### ISSUE TITLE
IEqualityComparers and Floor/Round and CeilToInt methods. 

### ISSUE THREAD

**Issue by EliasCK** [Unity-Technologies/Unity.Mathematics#20]
Good to see that the vector components are public fields instead of meaningless properties this time around :+1: Also nice to see that they have gotten the Serializable attributes as well.

Using structs as keys in HashSets and Dictionaries is pretty slow even if the struct has the IEquatable interface - they are still getting boxed (EDIT: they are not getting boxed, virtcalls on structs is just expensive). Providing a custom IEqualityComparer instance makes .Nets hash-tables a lot faster.

I find myself making them a lot, so would be really convenient if one as included, perhaps like so:

```
public partial class int3 : ...
{
    public static readonly Int3EqualityComparer DefaultEqualityComparer = new Int3EqualityComparer();

    public class Int3EqualityComparer : IEqualityComparer<int3>
    {
        public bool Equals(int3 a, int3 b)
        {
            return a.x == b.x && a.y == b.y && a.z == b.z;
        }

        public int GetHashCode(int3 v)
        {
            return ...
        }
    }
}
```

Would also be really convenient if int2, int3, and int4 had the FloorToInt, RoundToInt(v3) and CeilToInt methods. Just like Vector3Int

**Comment by AurelWu** [comment]
are you sure about it still causing boxing? I had the problem before when using Vector3Int as key and used Int3EqualityComparer but since using 2018.2 which added the IEquatable<Vector3Int> interface I could omit it and measured no performance loss. 

MSDN also says that if you do that then there is no boxing:
https://blogs.msdn.microsoft.com/jaredpar/2009/01/15/if-you-implement-iequatablet-you-still-must-override-objects-equals-and-gethashcode/

**Comment by EliasCK** [comment]
I'm pretty s
I wonder what the reason is for IEqualityComparer being so much faster then? Is it simply because calling a virtual method on the same instance multiple times is faster than calling a virtual method on multiple instances?

**Comment by EliasCK** [comment]
Aha. They are in fact not getting boxed, thanks! It looks like that reason that having a custom EqualityComparer is so much faster, is because you avoid an extra virtcall which is still a pretty expensive operation on structs apparently: Played around with it a bit: 

![image](https://user-images.githubusercontent.com/11874914/41808612-71be6150-76e0-11e8-8c7f-04eaea237000.png)

Don't know it's that slow, I guess it all depends on the runtime?

If you don't provide a custom IEqualityComparer, Dictioanry<T> and HashSet<T> will use the GenericEqualityComparer instead, which means that it'll first call the virtual comparer.Equals(a, b) method, which then calls the virtual Equals method from the IEquatable interface.

**Comment by deplinenoise** [comment]
This kind of functionality doesn't belong in a math library really - I'd encourage you to wrap these low-level types in a higher-level struct that you can use as a hash map key. That way you can customize hash codes, interfaces and everything else until you're happy.
