### ISSUE TITLE
Is it determinstic in different platform？Im just want to use burst to speed  up my deterministic math lib

### ISSUE THREAD

**Issue by MouseChannel** [Unity-Technologies/Unity.Mathematics#200]
I dont know how it likes in it？I know something like float3 or any float is not deternimistic. But others like int int3.Are those thing determinstic or not? so I can use mathematic as my dependence and enjoy burst compile

**Comment by unpacklo** [comment]
@MouseChannel The floating point types are not deterministic across platforms. The integer types are deterministic and implement the C# rules for underflow and overflow (if not, that's a bug).
