### ISSUE TITLE
Output of Mathf.Sign() and sign() differ in implementation

### ISSUE THREAD

**Issue by pointcache** [Unity-Technologies/Unity.Mathematics#21]
since Mathf.Sign returns -1 or 1, and sign() returns -1, 0 or 1 it creates problems for code 
where the result sign is then multiplied by something, effectively setting that value to zero.

This probably wont change as it's how it should be in shaders (probably) but still
having a classic (-1, 1) would be very nice.

Example of what current sign leads to
```cs

float num2 = sign(normalized.x * normalized2.y - normalized.y * normalized2.x);
float result = num * (num2 >= 0f ? 1f : -1f);

```

**Comment by xoofx** [comment]
Yes, It is matching the [GLSL and HLSL implementation of sign](https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx-graphics-hlsl-sign)

```
Returns -1 if x is less than zero; 0 if x equals zero; and 1 if x is greater than zero.
```

Not sure we would like to integrate another functions. @runestubbe thoughts?

**Comment by runestubbe** [comment]
I think we should stick to the HLSL/GLSL semantics for consistency with the rest of the library.
