### ISSUE TITLE
GetHashCode should be overridden for int2,int3,int4 to reduce collisions(also for the floats but probably less important there)

### ISSUE THREAD

**Issue by AurelWu** [Unity-Technologies/Unity.Mathematics#24]
example:
int3 val1 = new int3(3, 9,7);
int3 val2 = new int3(7, 3,9);
creates the same hash, I don't exactly know how the default hash code implementation looks like but from what I know it is really bad for structs and should never be used whenever Equals has been overridden.

the  old Vector2Int and Vector3Int classes have overridden the GetHashCode methods:

Vector3Int:     return x.GetHashCode() ^ (y.GetHashCode() << 2) ^ (z.GetHashCode() >> 2);
Vector2Int:     return x.GetHashCode() ^ (y.GetHashCode() << 2);

those however also are rather bad implementations as they have tons of collisions too:
for example all these Vector3Int have a hash value of 12 (there are definitely even more than those)
(2, 3, 9)
(2, 3, 10)
(2, 3, 11)
(4, 2, 2)
(4, 2, 3)

**Comment by runestubbe** [comment]
This has been fixed.
