### ISSUE TITLE
0.0.12-preview.10 has a compiler warnings which causes projects with warnaserror on to fail

### ISSUE THREAD

**Issue by mdouglass** [Unity-Technologies/Unity.Mathematics#25]
Our project has -warnaserror+ set in mcs.rsp.

Because of the following warning, we can not include the current release of Unity Mathematics as a dependency in our project (the warning gets converted to an error and the compile fails):

<anonymized>/packages/packages.unity.com/com.unity.mathematics@0.0.12-preview.10/Unity.Mathematics/Noise/psrdnoise2D.cs(100,20): error CS0219: Warning as Error: The variable `i2' is assigned but its value is never used

**Comment by runestubbe** [comment]
Fixed by Keijiro in June.

**Comment by mdouglass** [comment]
There's a new one now:

/Users/mdouglass/Library/Unity/cache/packages/packages.unity.com/com.unity.mathematics@0.0.12-preview.17/Unity.Mathematics/matrix.cs(90,20): error CS0219: Warning as Error: The variable `u2' is assigned but its value is never used

Would you prefer a new ticket?

**Comment by runestubbe** [comment]
That was fixed about a week ago. It will be in the next release.

**Comment by mdouglass** [comment]
Thanks, that's great!

Sorry to be the guy bugging you on this.  I really consider this an issue with the design of package manager -- I ought to be able to set warnaserror for my project without turning it on for every package I'm dependent on.  If you feel like adding comments on feature request 1066369 in the Unity Fogbugz I'd appreciate it ;)
