### ISSUE TITLE
Compiling for Linux

### ISSUE THREAD

**Issue by hyperion51** [Unity-Technologies/Unity.Mathematics#35]
Hi, I'm currently in the process of rewriting my game's math, and I'm using Unity.Mathematics to do so. Since my game requires the same formulas to be implemented in C# and HLSL, having a consistent syntax helps immensely.

My game is multiplayer, however, and I'd like to be able to use the same code on the server side, which is in a Linux environment. I've been implementing the server side code in .NET Core to ensure portability. Is there a way to use Unity.Mathematics in that project? Since Unity does support Linux, I'm assuming there's a workflow. Would I have to switch to Mono?

**Comment by deplinenoise** [comment]
You should be able to use mathematics from .NET Core. Let us know if it doesn't work.
