### ISSUE TITLE
Add ray and bounds types

### ISSUE THREAD

**Issue by tbg10101** [Unity-Technologies/Unity.Mathematics#36]
Requesting that bounds and ray types be added. (single- AND double-precision versions) with intersection functions. See: 

Types: 
- https://github.com/tbg10101/Unity.Mathematics/blob/extension/src/Unity.Mathematics/ray.cs
- https://github.com/tbg10101/Unity.Mathematics/blob/extension/src/Unity.Mathematics/bounds.cs

Intersection functions:
- https://github.com/tbg10101/Unity.Mathematics/blob/extension/src/Unity.Mathematics/math.cs#L184
- https://github.com/tbg10101/Unity.Mathematics/blob/extension/src/Unity.Mathematics/math.cs#L210

**Comment by deplinenoise** [comment]
Mathematics will stay low-level and higher-level abstractions will be relegated to extension packages.
