### ISSUE TITLE
Use plain constructors instead of function calls for static readonly

### ISSUE THREAD

**Issue by xoofx** [Unity-Technologies/Unity.Mathematics#42]
With the upcoming changes on our handling of static readonly, it is preferred to use only struct constructors instead of function calls to initialize static readonly.

Typically, these should be changed (they are in tests, so it's not a huge issue, but better keep it in mind for other cases through the codebase)

https://github.com/Unity-Technologies/Unity.Mathematics/blob/5a8c379f194de84897c81043bbb68d487ba94e9d/src/Unity.Mathematics.Tests/Tests/Shared/TestMatrix.cs#L450-L473

**Comment by runestubbe** [comment]
Done
