### ISSUE TITLE
Is there any documentation/steps to use HPC from plugins?

### ISSUE THREAD

**Issue by jdnichollsc** [Unity-Technologies/Unity.Mathematics#49]
Hi guys,

I'm the creator of this library https://github.com/proyecto26/RestClient
I was wondering if you could me suggestions, recommendations or any documentation to use HPC in my code in order to generate a better dll? And what happen if I have dependencies in my project?

Thanks in advance,
Nicholls

**Comment by deplinenoise** [comment]
This question seems to fit better in the general Unity data-oriented forums as it is unrelated to mathematics.
