### ISSUE TITLE
Implicit cast bonanza

### ISSUE THREAD

**Issue by andrew-raphael-lukasik** [Unity-Technologies/Unity.Mathematics#50]
Hi,
In my 2d grid system code I would like to have function overloads to let it's users provide grid coordinates in different formats, like:
```
void SetGridValue ( int x , int y , Value value ) => collection[ x , y ] = value;
void SetGridValue ( int2 xy , Value value ) => collection[ xy ] = value;//the same issue applies to indexer
void SetGridValue ( int i , Value value ) => collection[ i ] = value;
```
But since int can be implicitly cast to int2 without user knowledge I came to a conclusion that this would be a bad idea. My vote here thereby is to make this cast explicit since implicit introduces uncertainty between these types.

**Comment by andrew-raphael-lukasik** [comment]
I just discovered that **int** is implicitly cast to **float3**. I can understand this is handy when writing atomic shaders but I'm struggling to find enthusiasm for it when writing non-shaders.

**Comment by rikimaru0345** [comment]
void SetGridValue ( int2 xy , Value value ) => collection[ xy ] = value;//the same issue applies to indexer
    void SetGridValue ( int i , Value value ) => collection[ i ] = value;

I'm not sure if I can follow that example.

Either those two functions are supposed to work the same way (in which case switching from one overload to another should not cause any change in functionality)
or they are supposed to actually do different things (but then why are they designed as an overload, i.e. using the same name??).

Can you clarify? Maybe it's just an unfortunate example?

**Comment by andrew-raphael-lukasik** [comment]
> (...) those two functions are supposed to work the same way (...)
That is correct
> (...) in which case switching from one overload to another should not cause any change in functionality
That is the whole idea isn't it! And also the core of this issue I'm trying to raise here.

Imagine what happens when you remove one of the overloads at one point in the future. Imagine that won't throw any exception. This is very bad, bug-causing scenario. Because functionality of the other overload won't change at all, but values received and returned will (!)

To give another example. Here is, in my humble judgement, **too thin of a line between** "SetGridValue( 100 , value )" invoking this overload:
> void SetGridValue ( int i , Value value )
where first argument will be **int( 100 )**
and the other overload:
void SetGridValue ( int2 xy , Value value )
where first argument will be cast to **int2( 100 , 0 )**. While both overloads do the same job it is built on the assumption that input data is not being altered in any way.
Effectively rendering your code broken on any future refactor

**Comment by andrew-raphael-lukasik** [comment]
I'm not sure what more experienced programmers think of this. It well may be just a false alarm. But this subject creates some anxiety in my mind and I'm interested in hearing what to make of it or how to resolve it for good.

**Comment by rikimaru0345** [comment]
> This is the whole idea isn't it! And also the core of this issue I'm trying to raise here.
>
> Imagine what happens when you remove one of the overloads at one point in the future. Imagine a situation this won't throw any exception. This is potentially...

Yes, I get all that! Please don't get me wrong, I completely agree that a situation as you describe it would be horrible.

But the thing I want to know is (maybe I should have made that clearer from the start): do you have a situation like that already? How can it be that you have two APIs that take either an `int` or an `int2` as an indexer argument? Like do you **really** have a situation like that right now, or is it just a hypothetical example?

Also an implicit cast from `int` to `int2` will use the source value for **both** x and y! So `int2 a = 5;` will result in a `int2(5, 5)`.

I get your point in theory. But in my experience I've never seen this become an actual problem.
The programmer (you) will always be aware of potential implicit casts and keep that in mind for all API related decisions.

**Comment by andrew-raphael-lukasik** [comment]
> (...) in my experience I've never seen this become an actual problem.
> The programmer (you) will always be aware of potential implicit casts and keep that in mind for all API related decisions.

You might be right here. I have some doubts on consistency with the rest of c# where it's strongly typed and predictable. But I find if difficult to honestly argue with that without referring to just preference.

**Comment by andrew-raphael-lukasik** [comment]
<span><</span>two weeks later...<span>></span>
I'm taking back my self-doubt about this. It renders method overloading in C# broken. It removes productivity gains simple static code analysis used to provide. For what? A frivolous gain of little shorter code. Excuse me but I'm not writing shaders in C# to appreciate that.

**Comment by xoofx** [comment]
> My vote here thereby is to make this cast explicit since implicit introduces uncertainty between these types.

We won't change this behavior.

**Comment by andrew-raphael-lukasik** [comment]
Workaround: https://github.com/andrew-raphael-lukasik/Unity.Mathematics.Explicit
