### ISSUE TITLE
[Feature Request] Ref column indexers for matrices.

### ISSUE THREAD

**Issue by MHDante** [Unity-Technologies/Unity.Mathematics#51]
Hi, I've been (ill-advisedly) using some of your codegen to create larger matrices for linear algebra stuff. Pretty cool so far. One thing I've found, is that the `floatN this[int i]` indexer on matrices does not allow setting of individual members due to returning a struct by value. e.g: this doesn't work: 

    myNxnMatrix[2][3] = 9;

This is fairly expected, but I've found that if you used a `ref floatN this[int i]` you'd be able to allow for that kind of nested indexing, and even use the indexed column as a modifiable lvalue. In my case, I use it to avoid copying float9 vectors.

This also removes the need for the setter.

Best of all, the indexer would still make copies at the call site unless the ref keyword is explicitly used, so as to avoid unintentional modifications of the matrix.

**Comment by deplinenoise** [comment]
What is the issue exactly?

**Comment by MHDante** [comment]
Sorry if I wasn't clear. I was suggesting an improvement to the API by changing matrix indexers to be ref returns.
