### ISSUE TITLE
Comparing float2s in if(...) is awkward and cumbersome

### ISSUE THREAD

**Issue by Koopa1018** [Unity-Technologies/Unity.Mathematics#63]
Frequently, I will attempt to compare a float2 and a float2 in an if statement, only to find that the comparison yields a bool2 rather than a bool.

This seems like logical behavior, now that I'm used to it--but there doesn't seem to be any elegant way to convert bool2 to bool so it can be used like this.

I would expect one of the following:
- Bool2 has methods `And()`, `Or()`, `Xor()` that can be called directly and return bools. Perhaps syntactically ugly--`if ((myPos != otherPos).And())`--but this would be my preferred behavior.
- Bool2 automatically converts to bool by performing AND or some such on its components. I can understand why this is not done, given that no default behavior would work for every case.
- Comparing bool2 and bool2 returns `true` if all components are equal, `false` otherwise, the same way Vector2 == Vector2 works.

But none of these appears to be the case.

At present, I am forced either to cache the bool2 in a variable and compare its components in the `if (...)` statement, or to directly compare the components of the float2s. Functional ways to code, certainly, but unpleasant to look at, especially given the prior compactness and understandibility of comparing Vector2 and Vector2.

Any thoughts on this? Am I missing some existing method to do this? And are these unpleasantly lengthy methods superior in some way, or at least intended?

**Comment by xoofx** [comment]
> This seems like logical behavior, now that I'm used to it--but there doesn't seem to be any elegant way to convert bool2 to bool so it can be used like this.

The pattern is to use `math.all` (or math.any depending on your case) as it is the case when you are programming with HLSL.

``` 
if (all(vec1 == vec2)) {
  ...
}
```
