### ISSUE TITLE
[Feature Request] Add explicit conversion from euler to quaternion with rotation order

### ISSUE THREAD

**Issue by mecanimdev** [Unity-Technologies/Unity.Mathematics#74]
There is no explicit conversion from euler to quaternion, we need to convert to float3x3 first and then to quaternion.

As a first iteration we could only provide a methods that does the implicit conversion and improve it later.

```
public quaternion FromEuler(float3 xyz, RotationOrder order = RotationOrder.Default)
{
    return new quaternion( float3x3.Euler(xyz, order));
}
```

**Comment by unpacklo** [comment]
I may be confused, but Isn't this the function you're looking for?

<img width="907" alt="image" src="https://user-images.githubusercontent.com/3121968/78198387-53719080-743d-11ea-9cd0-3071a573a051.png">

**Comment by mecanimdev** [comment]
yes, it was added recently?

**Comment by unpacklo** [comment]
It looks like it was implemented in 2018.  I'll go ahead and close this issue.
