### ISSUE TITLE
Double-precision quaternions

### ISSUE THREAD

**Issue by NovaSilisko** [Unity-Technologies/Unity.Mathematics#82]
I've begun the slow and careful process of converting my project over to the Mathematics library (from double variants of Unity's Vector3 and Quaternion I found years ago), but I've realized there's an upcoming roadblock. I use the double-precision quaternions quite a lot (the joy of working with 1:1 scale celestial mechanics), but I don't see such a thing in this library.

I can roll my own relatively easy based on the single-precision code here, but it's a bit of an unexpected omission considering how comprehensive everything else is. Me and the ~4 other people on earth who need this would appreciate it!

**Comment by joeante** [comment]
There is no plan for this.

**Comment by imzahahs** [comment]
Need this for orbital calculations.
