### ISSUE TITLE
Add function to extract float3x3 from float4x4

### ISSUE THREAD

**Issue by unpacklo** [Unity-Technologies/Unity.Mathematics#89]
It doesn't appear that we have a convenience function to extract the upper left float3x3 from a float4x4.  Currently you must extract manually:

`return new float3x3(m.c0.xyz, m.c1.xyz, m.c2.xyz);`

Add this as a convenience function.

**Comment by tlaedre** [comment]
In the spirit of HLSL, shouldn't there be an explicit cast implemented from float4x4 to float3x3?

**Comment by unpacklo** [comment]
Yes, I think being able to do both of these would be good:

`var f3x3 = new float3x3(f4x4);`
`var f3x3 = (float3x3)f4x4;`
