### ISSUE TITLE
Double Precision Request

### ISSUE THREAD

**Issue by tbg10101** [Unity-Technologies/Unity.Mathematics#9]
I'd like to see double precision options here as well. (math operations for doubles, double2, double3, double4, etc.)

**Comment by caedriel** [comment]
Herbal space program has a public repository of double precision math library

**Comment by starikcetin** [comment]
This would be a very nice addition. I can already see how beneficial this would be for open world and space simulation games.

**Comment by caedriel** [comment]
https://hackage.haskell.org/package/KSP-0.1#readme

this is as close as we can get since their repo was made private while back by take two interactive

**Comment by tbg10101** [comment]
I got impatient and did a lot tonight: https://github.com/tbg10101/Unity.Mathematics/commit/705af97a178d38dd1cd3cc84f560390bf3b5aff0

No idea if it works with the Burst compiler or not, will see if I can test tomorrow.

**Comment by tbg10101** [comment]
In case anyone else is actually using the double-precision types (and rays, bounds, etc.) that I added, I set up a new branch that can be plopped next to the officially released unity.mathematics package, so you can use it directly in your Unity projects: https://github.com/tbg10101/Unity.Mathematics/tree/extension

It even implements some of the methods that aren't implemented yet, like lerp and slerp for quaternions. (see the math_x class)

I have only tested it next to the 0.0.12-preview.5 version so you mileage may vary.

**Comment by tbg10101** [comment]
I think this can be closed since double vectors have been added. (and I updated my fork's [extension branch](https://github.com/tbg10101/Unity.Mathematics/tree/extension) to extend 0.0.12-preview.19, for anyone who was using it)

**Comment by runestubbe** [comment]
Doubles are now supported in both Mathematics and Burst, so I will close this issue.

**Comment by gotmachine** [comment]
Still missing double precision quaternion...
