### ISSUE TITLE
Unity.Mathematics.noise.snoise(float3) has very bad perf

### ISSUE THREAD

**Issue by khyperia** [Unity-Technologies/Unity.Mathematics#94]
The other implementation of simplex noise I'm using as a benchmark is found here, using the `Generate(float, float, float)` method: https://github.com/WardBenjamin/SimplexNoise/blob/2afa9a63483562cc4c0a95bbfa6b183fc256a790/SimplexNoise/Noise.cs

The other implementation is **16 times** faster than `noise.snoise`. I'm assuming the other overloads in `noise.snoise` are similarly slow, and possibly other functions in `noise`, I'm hoping we can do a performance investigation on all of them.

A real-world performance case (where I did a simple swap of implementations, which is how I discovered this) is 5-8 times slower (the work being measured there involves a lot of compute not calling the noise func), so this isn't just a quirk of this perf test case.

---

The testing method is:

```C#
const int COUNT = 1000000;
var stopwatch = Stopwatch.StartNew();
for (var i = 0; i < COUNT; i++)
{
    Unity.Mathematics.noise.snoise(new Unity.Mathematics.float3(1, 1, 1));
}
UnityEngine.Debug.Log("unity's: " + stopwatch.Elapsed.TotalMilliseconds / COUNT * 1000);
stopwatch.Restart();
var asdf = new SimplexNoise(382901, 1);
for (var i = 0; i < COUNT; i++)
{
    asdf.Sample3D(1, 1, 1);
}
UnityEngine.Debug.Log("WardBenjamin's: " + stopwatch.Elapsed.TotalMilliseconds / COUNT * 1000);
```

which is called 10 times, and the timing average taken. The code is running in a release player build in `2019.3.0f3`.

Actual data I collected:

```
Unity's timings (μs):
2.0875775
2.0676362
2.0696992
2.0668478
2.0464833
2.1096326
2.0688119
2.0798716
2.0344471
2.0873375

WardBenjamin's timings (μs):
0.125486
0.1248664
0.1252765
0.1261635
0.1316784
0.1296202
0.1282871
0.1263121
0.125543
0.1261868

Unity's mean time: 2.07183447μs
Unity's stdev: 0.02128683979
WardBenjamin's mean time: 0.126942μs
WardBenjamin's stdev: 0.002214794701
Ratio of means: 16.32111098 times faster
```

**Comment by unpacklo** [comment]
Is it possible for you to Burst compile your code?

If you don't use Burst to compile your code, you will see very poor performance for many Unity.Mathematics functions.  Unity.Mathematics wasn't designed for high performance if you aren't Burst compiling but we recognize that running Mono is an important case so we'll be investigating what we can do there in the future.

**Comment by khyperia** [comment]
Thanks for clarifying! I guess I didn't realize this:

> Unity.Mathematics wasn't designed for high performance

so I'll close this as this is just a minor aspect of that larger decision, doesn't really make sense to look at only the noise functions in isolation.
